import { Response } from "express";
import { prisma } from "../config/db.js";
import { AuthenticatedRequest } from "../middleware/auth.js";

const UNRESTRICTED_ROLES = ["SUPER_ADMIN", "SUPER_ADMIN_IT"];

export async function getAuditLogs(req: AuthenticatedRequest, res: Response): Promise<void> {
  const { category, status } = req.query;

  if (!req.user) {
    res.status(401).json({ success: false, message: "Unauthorized" });
    return;
  }

  try {
    const whereClause: Record<string, unknown> = {
      category: category ? (category as any) : undefined,
      status: status ? (status as any) : undefined
    };

    // Bank Managers only see audit events generated by their own branch staff
    if (!UNRESTRICTED_ROLES.includes(req.user.role)) {
      if (!req.user.branchId) {
        res.status(200).json({ success: true, data: [] });
        return;
      }
      whereClause.actor = { branchId: req.user.branchId };
    }

    const logs = await prisma.systemAuditLog.findMany({
      where: whereClause,
      include: {
        actor: {
          select: { username: true, fullName: true, role: true }
        }
      },
      orderBy: { timestamp: "desc" }
    });

    const formatted = logs.map(l => ({
      id: l.id,
      timestamp: l.timestamp,
      actorId: l.actorId,
      actorName: l.actor.fullName,
      actorRole: l.actor.role,
      action: l.action,
      category: l.category,
      ipAddress: l.ipAddress,
      details: l.details,
      status: l.status
    }));

    res.status(200).json({ success: true, data: formatted });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || "Failed to retrieve security audit trail" });
  }
}

export async function getSecurityMetrics(req: AuthenticatedRequest, res: Response): Promise<void> {
  if (!req.user) {
    res.status(401).json({ success: false, message: "Unauthorized" });
    return;
  }

  try {
    const whereClause: Record<string, unknown> = {};

    if (!UNRESTRICTED_ROLES.includes(req.user.role)) {
      if (!req.user.branchId) {
        res.status(200).json({
          success: true,
          data: {
            totalSecurityEvents: 0,
            criticalThreatAlerts: 0,
            systemWarnings: 0
          }
        });
        return;
      }
      whereClause.actor = { branchId: req.user.branchId };
    }

    const logs = await prisma.systemAuditLog.findMany({ where: whereClause });
    const failures = logs.filter(l => l.status === "FAILURE").length;
    const warnings = logs.filter(l => l.status === "WARNING").length;

    res.status(200).json({
      success: true,
      data: {
        totalSecurityEvents: logs.length,
        criticalThreatAlerts: failures,
        systemWarnings: warnings
      }
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || "Failed to compile security metrics" });
  }
}
